run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocritic
    - bodyclose
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - exportloopref
    - unconvert

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: false
  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
