version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocritic
    - bodyclose
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - exportloopref
    - unconvert

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
