version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - gocritic
    - bodyclose
    - noctx
    - sqlclosecheck
    - rowserrcheck
    - unconvert
  
  settings:
    errcheck:
      check-blank: true
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: false
    gosec:
      excludes:
        - G404

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
