package config

import "time"

// DefaultConfig returns a Config with sensible default values
func DefaultConfig() *Config {
	return &Config{
		RouterType: "gin",
		Service: ServiceConfig{
			Name:        "app",
			Environment: "production",
		},
		HTTP: HTTPConfig{
			Port:           8080,
			ReadTimeout:    30 * time.Second,
			WriteTimeout:   30 * time.Second,
			IdleTimeout:    120 * time.Second,
			MaxRequestSize: 1 << 20, // 1 MiB
		},
		Management: ManagementConfig{
			Enabled:      true,
			Port:         9090,
			ReadTimeout:  10 * time.Second,
			WriteTimeout: 10 * time.Second,
			AuthEnabled:  false,
			MTLSEnabled:  false,
			TLSCertFile:  "",
			TLSKeyFile:   "",
			TLSCAFile:    "",
		},
		CORS: CORSConfig{
			Enabled:                   false,
			AllowAllOrigins:           false,
			AllowOrigins:              []string{},
			AllowMethods:              []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"},
			AllowPrivateNetwork:       false,
			AllowHeaders:              []string{},
			ExposeHeaders:             []string{},
			AllowCredentials:          false,
			MaxAge:                    12 * time.Hour,
			AllowWildcard:             false,
			AllowBrowserExtensions:    false,
			CustomSchemas:             []string{},
			AllowWebSockets:           false,
			AllowFiles:                false,
			OptionsResponseStatusCode: 204,
		},
		SecurityHeaders: SecurityHeadersConfig{
			Enabled:                   true,
			IsDevelopment:             false,
			AllowedHosts:              []string{},
			SSLRedirect:               false,
			SSLTemporaryRedirect:      false,
			SSLHost:                   "",
			SSLProxyHeaders:           map[string]string{"X-Forwarded-Proto": "https"},
			DontRedirectIPV4Hostnames: true,
			STSSeconds:                31536000,
			STSIncludeSubdomains:      true,
			STSPreload:                false,
			CustomFrameOptions:        "DENY",
			ContentTypeNosniff:        true,
			ContentSecurityPolicy:     "default-src 'self'",
			ReferrerPolicy:            "strict-origin-when-cross-origin",
			PermissionsPolicy:         "geolocation=()",
			IENoOpen:                  true,
			XDNSPrefetchControl:       "off",
			CrossOriginOpenerPolicy:   "same-origin",
			CrossOriginResourcePolicy: "same-origin",
			CrossOriginEmbedderPolicy: "",
			CustomHeaders:             map[string]string{},
		},
		Security: SecurityConfig{
			HTTPSignature: HTTPSignatureConfig{
				Enabled:         false,
				KeyIDHeader:     "X-Key-Id",
				TimestampHeader: "X-Timestamp",
				NonceHeader:     "X-Nonce",
				SignatureHeader: "X-Signature",
				MaxClockSkew:    5 * time.Minute,
				NonceTTL:        10 * time.Minute,
				RequireNonce:    true,
				ExcludedPathPrefixes: []string{
					"/health",
					"/metrics",
					"/ready",
					"/version",
				},
				StaticKeys: map[string]string{},
			},
		},
		I18n: I18nConfig{
			Enabled:          false,
			DefaultLocale:    "en",
			SupportedLocales: []string{"en"},
			QueryParam:       "lang",
			HeaderName:       "X-Locale",
			FallbackMode:     "base",
			CatalogPath:      "",
		},
		Session: SessionConfig{
			Enabled:        false,
			Store:          "inmemory",
			TTL:            12 * time.Hour,
			IdleTimeout:    30 * time.Minute,
			CookieName:     "sid",
			CookiePath:     "/",
			CookieDomain:   "",
			CookieSecure:   true,
			CookieHTTPOnly: true,
			CookieSameSite: "lax",
			AutoCreate:     true,
			Redis: SessionRedisConfig{
				MaxConns:         10,
				OperationTimeout: 5 * time.Second,
				Prefix:           "session",
			},
			Memcached: SessionMemcachedConfig{
				Addresses: []string{},
				Timeout:   500 * time.Millisecond,
				Prefix:    "session",
			},
		},
		CSRF: CSRFConfig{
			Enabled:        false,
			HeaderName:     "X-CSRF-Token",
			CookieName:     "XSRF-TOKEN",
			CookiePath:     "/",
			CookieDomain:   "",
			CookieSecure:   true,
			CookieSameSite: "lax",
			CookieTTL:      12 * time.Hour,
			ExemptMethods:  []string{"GET", "HEAD", "OPTIONS", "TRACE"},
			ExemptPaths:    []string{},
		},
		SSE: SSEConfig{
			Enabled:               false,
			Endpoint:              "/events",
			Store:                 "inmemory",
			Bus:                   "none",
			ReplayLimit:           100,
			ClientBuffer:          64,
			MaxConnections:        10000,
			HeartbeatInterval:     20 * time.Second,
			DefaultRetryMS:        3000,
			DropOnBackpressure:    true,
			ChannelQueryParam:     "channel",
			TenantQueryParam:      "tenant",
			SubjectQueryParam:     "subject",
			LastEventIDQueryParam: "last_event_id",
			Redis: SSERedisConfig{
				MaxConns:         10,
				OperationTimeout: 3 * time.Second,
				HistoryPrefix:    "sse:history",
				PubSubPrefix:     "sse:bus",
			},
			EventBus: SSEEventBusConfig{
				TopicPrefix:      "sse",
				OperationTimeout: 5 * time.Second,
			},
		},
		Email: EmailConfig{
			Enabled:  false,
			Provider: "smtp",
			SMTP: EmailSMTPConfig{
				Host:               "",
				Port:               587,
				Username:           "",
				Password:           "",
				From:               "",
				EnableTLS:          false,
				InsecureSkipVerify: false,
				OperationTimeout:   10 * time.Second,
			},
			SES: EmailSESConfig{
				Region:           "",
				Endpoint:         "",
				AccessKeyID:      "",
				SecretAccessKey:  "",
				SessionToken:     "",
				From:             "",
				OperationTimeout: 10 * time.Second,
			},
			SendGrid: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://api.sendgrid.com",
				OperationTimeout: 10 * time.Second,
			},
			Mailgun: EmailMailgunConfig{
				Token:            "",
				Domain:           "",
				From:             "",
				BaseURL:          "https://api.mailgun.net",
				OperationTimeout: 10 * time.Second,
			},
			Mailchimp: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://mandrillapp.com/api/1.0",
				OperationTimeout: 10 * time.Second,
			},
			MailerSend: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://api.mailersend.com",
				OperationTimeout: 10 * time.Second,
			},
			Postmark: EmailPostmarkConfig{
				ServerToken:      "",
				From:             "",
				BaseURL:          "https://api.postmarkapp.com",
				OperationTimeout: 10 * time.Second,
			},
			Mailtrap: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://send.api.mailtrap.io",
				OperationTimeout: 10 * time.Second,
			},
			SMTP2GO: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://api.smtp2go.com",
				OperationTimeout: 10 * time.Second,
			},
			SendPulse: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://api.sendpulse.com",
				OperationTimeout: 10 * time.Second,
			},
			Brevo: EmailTokenConfig{
				Token:            "",
				From:             "",
				BaseURL:          "https://api.brevo.com",
				OperationTimeout: 10 * time.Second,
			},
			Mailjet: EmailMailjetConfig{
				APIKey:           "",
				APISecret:        "",
				From:             "",
				BaseURL:          "https://api.mailjet.com",
				OperationTimeout: 10 * time.Second,
			},
		},
		Auth: AuthConfig{
			Enabled:      false, // Disabled by default, enable via config
			JWKSCacheTTL: 1 * time.Hour,
			Claims: AuthClaimsConfig{
				Mappings: map[string][]string{
					"subject":   {"sub"},
					"issuer":    {"iss"},
					"audience":  {"aud"},
					"scopes":    {"scope", "scopes"},
					"roles":     {"role", "roles"},
					"tenant_id": {"tenant_id", "tenantId"},
				},
			},
		},
		Database: DatabaseConfig{
			MaxOpenConns:    25,
			MaxIdleConns:    5,
			ConnMaxLifetime: 5 * time.Minute,
			ConnMaxIdleTime: 2 * time.Minute,
			QueryTimeout:    10 * time.Second,
			ConnectTimeout:  5 * time.Second,
		},
		Cache: CacheConfig{
			MaxConns:         10,
			OperationTimeout: 5 * time.Second,
		},
		ObjectStorage: ObjectStorageConfig{
			Enabled: false,
			Type:    "s3",
			S3: ObjectStorageS3Config{
				Bucket:           "",
				Region:           "eu-west-1",
				Endpoint:         "",
				AccessKeyID:      "",
				SecretAccessKey:  "",
				SessionToken:     "",
				UsePathStyle:     false,
				OperationTimeout: 10 * time.Second,
				PresignExpiry:    15 * time.Minute,
			},
		},
		Search: SearchConfig{
			Driver:           "http",
			MaxConns:         10,
			OperationTimeout: 5 * time.Second,
			AWSService:       "es",
		},
		EventBus: EventBusConfig{
			Serializer:       "json",
			OperationTimeout: 30 * time.Second,
			GroupID:          "default-consumer-group",
			Exchange:         "events",
			ExchangeType:     "topic",
			WaitTimeSeconds:  10,
			MaxMessages:      10,
		},
		Jobs: JobsConfig{
			Backend: JobsBackendEventBus,
		},
		Validation: ValidationConfig{
			Kafka: KafkaValidationConfig{
				Enabled:        false,
				Mode:           "enforce",
				DescriptorPath: "events/proto/schema.pb",
				DefaultPolicy:  "BACKWARD",
				Subjects:       map[string]string{},
			},
		},
		Observability: ObservabilityConfig{
			LogLevel:          "info",
			LogFormat:         "json",
			ServiceName:       "",
			TracingEnabled:    false, // Disabled by default, enable via config
			TracingSampleRate: 0.1,
			AsyncLogging: AsyncLoggingConfig{
				Enabled:      false,
				QueueSize:    1024,
				WorkerCount:  1,
				DropWhenFull: true,
			},
			RequestLogging: RequestLoggingConfig{
				Enabled:              true,
				LogStart:             true,
				Output:               "logger",
				Fields:               []string{"request_id", "method", "path", "status", "duration_ms", "remote_addr", "error"},
				ExcludedPathPrefixes: []string{},
				PathPolicies:         []RequestLogPathPolicy{},
			},
			RequestTracing: RequestTracingConfig{
				Enabled:              true,
				ExcludedPathPrefixes: []string{},
				PathPolicies:         []RequestTracePathPolicy{},
			},
			RequestTimeout: RequestTimeoutConfig{
				Enabled:              false,
				Default:              15 * time.Second,
				ExcludedPathPrefixes: []string{},
				PathPolicies:         []RequestTimeoutPathPolicy{},
			},
		},
		RateLimit: RateLimitConfig{
			Enabled:           false,
			Type:              "local",
			RequestsPerSecond: 100,
			Burst:             20,
			Window:            1 * time.Second,
			Redis: RateLimitRedisConfig{
				MaxConns:         10,
				OperationTimeout: 5 * time.Second,
				Prefix:           "ratelimit",
			},
		},
		Swagger: SwaggerConfig{
			Enabled:  false,
			SpecPath: "/api/openapi/openapi.yaml",
		},
	}
}
