#!/bin/bash
set -e

echo "=== Adding missing comments for exported types ==="

# Files already fixed manually
echo "✓ pkg/config/config.go - database/eventbus/jobs constants"
echo "✓ pkg/config/provider.go - ConfigProvider methods"
echo "✓ pkg/email/factory.go - provider constants"
echo "✓ pkg/eventbus/envelope.go - event constants"
echo "✓ pkg/eventbus/aggregate_versioning.go - version status"
echo "✓ pkg/jobs/backend.go - job headers"
echo "✓ pkg/jobs/contract.go - job constants"
echo "✓ pkg/middleware/logging/logging.go - logging constants"

echo ""
echo "Remaining files to fix manually:"
echo "- pkg/cli/main.go (PolicyAlways, LoadConfigAndLogger)"
echo "- pkg/auth/jwt.go (JWKSValidatorOption)"
echo "- pkg/eventbus/idempotency.go (DefaultProcessedEventsRetention)"
echo "- pkg/eventbus/outbox.go (DefaultOutboxPollInterval)"
echo "- pkg/eventbus/retry_dlq.go (DefaultRetryMaxRetries)"
echo "- pkg/eventbus/schema/contract.go (ValidationMode, CompatibilityPolicy)"
echo "- pkg/health/checkers.go (HealthCheckable)"
echo "- pkg/health/registry.go (Status constants)"
echo "- pkg/middleware/authz/authz.go (DefaultTenantHeader, ClaimValueSource)"
echo "- pkg/middleware/cache/cache.go (KeySource, CacheKeyRule)"
echo "- pkg/middleware/i18n/i18n.go (LocaleContextKey)"
echo "- pkg/middleware/ratelimit/ratelimit.go (RateLimitConfig)"
echo "- pkg/middleware/timeout/timeout.go (ModeOff)"
echo "- pkg/middleware/tracing/tracing.go (TracingConfig, ModeOff)"
echo "- pkg/observability/logger/zap.go (LogLevel, LogFormat, DefaultConfig)"
echo "- pkg/observability/tracing/spans.go (SpanOperation constants)"
echo "- pkg/realtime/ws/ws.go (OpText, Config, Conn methods)"
echo "- pkg/repository/crud.go (SortOrder)"
echo "- pkg/scheduler/runtime.go (DefaultDispatchTimeout)"
echo "- pkg/scheduler/task.go (MisfirePolicy)"
echo "- pkg/server/bootstrap.go (NewDefaultRunHTTPServersOptions)"
echo "- pkg/server/management.go (Router method)"
echo "- pkg/server/public.go (Router method)"
echo "- pkg/server/server.go (ServerConfig)"
echo "- pkg/store/*/adapter.go (adapter types)"

echo ""
echo "Run: golangci-lint run --disable-all -E revive | grep 'should have comment' > remaining-comments.txt"
echo "to get full list of remaining issues"
