#!/bin/sh

# Run golangci-lint on staged Go files
STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -z "$STAGED_GO_FILES" ]; then
  exit 0
fi

golangci-lint run --new-from-rev=HEAD~ --config=.golangci.yml

if [ $? -ne 0 ]; then
  echo "golangci-lint failed. Please fix the issues before committing."
  exit 1
fi

exit 0
